### ISSUE TITLE
Add docs for the env field used in the IQE CJI

### ISSUE THREAD

**Issue by juandspy** [RedHatInsights/bonfire#328]
As part of https://github.com/RedHatInsights/clowder/pull/855 a new `env` field was added to the IQE CJI. I see 2 issues here:

1. It is not clear how to use this new `env` field. Could you please add one example? For example, as part of [CCXDEV-11427](https://issues.redhat.com/browse/CCXDEV-11427), I'm interested in passing `DYNACONF_USER_PROVIDER__rbac_enabled=false` to the IQE CJI in my `pr_check.sh`.
2. I can't see the `env` in the [default-iqe-cji.yaml](https://github.com/RedHatInsights/bonfire/blob/master/bonfire/resources/default-iqe-cji.yaml).

**Comment by bsquizz** [comment]
#329 hopefully serves as a good example -- I'll release those changes next week after testing and confirming that the version of clowder that supports 'env' is running on all environments.

As a follow-up, we may want to add the ability to add some custom additional env vars on the fly with bonfire... a work-around you can use currently is to define your own CJI template file rather than using the default template that ships with bonfire. When you run `bonfire deploy-iqe-cji` or `bonfire process-iqe-cji` you can use the `--template-file` argument:

```
  --template-file TEXT          Path to ClowdJobInvocation template file
                                (default: use IQE CJI template packaged with
                                bonfire)
```
